export enum QueryKeys {
    LOGIN = 'login',
    REGISTRATION = 'registration',
    GET_ADS = 'get-ads',
    GET_USER_ADS = 'get-user-ads',
    GET_ONE_AD = 'get-one-ad',
    GET_AD_COMMENTS = 'get-ad-comments',
    GET_ALL_COMMENTS = 'get-all-comments',
    GET_ALL_USERS = 'get-all-users',
    GET_CURRENT_USER = 'get-current-user',
    ADD_ITEM_WITHOUT_IMGS = 'add-item-without-imgs',
    ADD_ITEM_WITH_IMGS = 'add-item-with-imgs',
    ADD_IMG_TO_ITEM = 'add-img-to-item',
    ADD_COMMENT_TO_ITEM = 'add-comment-to-item',
    CHANGE_ITEM_TEXT = 'change-item-text',
    CHANGE_USER_DATA = 'change-user-data',
    CHANGE_USER_IMG = 'change-user-img',
    CHANGE_PASSWORD = 'change-password',
    DELETE_ITEM = 'delete-item',
    DELETE_IMAGE = 'delete-image',
}
